# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 17:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='journal/')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
    ]
