# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 04:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('when', models.CharField(max_length=20)),
                ('what', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='about/')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
            ],
        ),
    ]
